### PR TITLE
Missing Directory Reference in Demo

### PR DESCRIPTION
**Pull request by dual-sharks**
Directory refers to a folder not found.  Running `modal serve \main.py` returns the following:
`Stopping app - uncaught exception raised locally: FileNotFoundError(PosixPath('/Users/.../vision-is-all-you-need/frontend/dist')).`

Removing this allows the completion and resolution of this execution.

### CODE REVIEW

**Comment by skvark** [comment]
The `dist` directory is needed for the full Modal deployment. You can create it by running `npm install` and `npm run build` in the `frontend` dir. A better option would be to create the `dist` directory into the repo and add e.g. `.gitkeep` dummy file there.

**Comment by dual-sharks** [comment]
@skvark I removed the removal - you are right, running those does run it. I'm having problems connecting the back end and front end together. I do think that the other change is correct, in terms of `modal serve \main.py`

**Comment by skvark** [comment]
Yes, that change is most likely correct. When running "locally" with the `modal serve` command you will get a backend URL from Modal cloud. 

To make the locally running front end query against that, you need to:

1. Run `modal serve main.py` -> copy the URL you get in console
2. Create `.env.development` file to the frontend dir
3. Add there the copied url `VITE_BACKEND_URL=https://your-modal-dev-instance-from-serve-main-command.modal.run/`
4. `npm run dev`
5. http://localhost:5173 frontend should now query the URL that was set to `VITE_BACKEND_URL`

**Comment by dual-sharks** [comment]
That was my mistake - I added that file to the main directory instead of front end. 
And okay, great, could you merge? Very interested in this project, happy to contribute.

**Comment by skvark** [comment]
Thanks for the PR!

**Comment by dual-sharks** [comment]
Of course, very interested in your use case here - will continue looking
into this and contributing where I can.

**Pull request merged**
